import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway, Montserrat } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import AuthProvider from "@/providers/AuthProviders";
import Navbar from "@/components/shared/Navbar";

const montserratHeading = Montserrat({subsets:['latin'],variable:'--font-heading'});

const raleway = Raleway({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rent Nest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", raleway.variable, montserratHeading.variable)}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
         <Toaster />
         <AuthProvider>
            <Navbar />
            <main className="flex-1 flex flex-col">{children}</main>
         </AuthProvider>
        
        </body>
    </html>
  );
}
